### ISSUE TITLE
Add custom category for mod items under BodyPartsArtificial

### ISSUE THREAD

**Issue by kaptain-kavern** [kaptain-kavern/ADogSaid#10]
Maybe Animal Artificial Body Parts ?

**Comment by kaptain-kavern** [comment]
``` xml
  <ThingCategoryDef>
    <defName>BodyPartsAnimalArtificial</defName>
    <label>Animal Body Part</label>
    <parent>BodyPartsArtificial</parent>
  </ThingCategoryDef>
```

Something like that in _ThingCatecoryDefs_

**Comment by kaptain-kavern** [comment]
This is done

![Custom Category](https://i.imgur.com/gd18hvG.jpg)

Will be in next update (and already on [Dev Branche](https://github.com/kaptain-kavern/ADogSaid/tree/Dev))

@spoonshortage could you test it please? 
It works on my PC but i don't want to redo a false update like yesterday :stuck_out_tongue_winking_eye:   (You just have to click on **_Clone or Download_** from the [Dev Branche](https://github.com/kaptain-kavern/ADogSaid/tree/Dev)) pages

**Comment by inkyspoon** [comment]
ok just tested, all works fine with ccl and epoe. :)

**Comment by inkyspoon** [comment]
rimworld on steam just had an update though to 0.14.1241 might wanna check that too?

**Comment by kaptain-kavern** [comment]
Thanks, nice.

Yeah you read my mind. I tested it with EPOE as i would like to use it for implementing more artificial parts **_more_** easily (i don't know if you read my Wall of Text in #11 ^^

And for modding compatibility i'll always use CCL (i was hanging with the two main modders - **E** a.k.a. **1000101** and **Skullywag** - on the slack since the beginning of the project and they really have a vision of simplified modding environment . To me, nearly half of the released mods since A11/A12 couldn't have be done without those guys ^^ )

---

Yes please. I don't have Steam and waiting for my download link via sendOwl(mail) :p but from what i've read this should be ok i guess

**Comment by inkyspoon** [comment]
yes I did read it ^^ I try to read everything, its just that I'm still learning on the whole matter and I try to help where I can :)

**Comment by kaptain-kavern** [comment]
Cool i spend nearly one hour (cause i'm not a natural english speaker) to write it. But it was in the purpose that it will help you understand

**Comment by kaptain-kavern** [comment]
Will be in next update
