### ISSUE TITLE
How about Xenogreffes?

### ISSUE THREAD

**Issue by kaptain-kavern** [kaptain-kavern/ADogSaid#13]
Harvest organs on some animals in order to save colonist. (or the other way :p )

On pig (so boar too ?) / monkey / maybe the megatherium (as he as `<body>Human</body>` in code  -  [here line 159](https://github.com/kaptain-kavern/ADogSaid/blob/master/Defs/ThingDefs_Races/Races_Animal_Giant.xml))

**Comment by inkyspoon** [comment]
Not sure bout that. I wouldn't want the mod to get to complicated if Im honest. also wasnt there that bug in latta's a12 version or so, where people complained they could attach chicken legs to people etc..xD
