### ISSUE TITLE
[DEBATE]Let's try clarifying what part we want

### ISSUE THREAD

**Issue by kaptain-kavern** [kaptain-kavern/ADogSaid#14]
_Ok @spoonshortage correct me if needed (i guess you can edit this text, even)_

So far we are going to make thing simple. "2 tech levels" for each animal parts (equivalent to Prosthetic part/Bionic part in Vanilla) - If it's relevant/possible

To me, bionics should perform better than natural part and prosthetics a little bit lesser (like 80%/90%).

---

| Natural Organ | Prosthetic version | Bionic Version |
| --- | --- | --- |
| Eye |  | **bionic eye** |
| Arm | **simple prosthetic animal arm** | **bionic animal arm** |
| Leg | **simple prosthetic animal leg** | **bionic animal leg** |
| Jaw | _simple jaw_ (can this use denture Hediff already) | ?`Bionic jaw (increase eating speed + damage)`? |
| Brain | `no prosthetic brains i guess` :p | _Brain Simulator_ |
| Spine | _simple spine_ | ?`Bionic Spine (increase speed + ???)`? |
| Ear |  | _Bionic ears_ |
| Heart |  |  |
| Lung |  |  |

In **BOLD** : things that are already in 1.0
In _ITALIC_ : things that we have already discussed/planed
In `CODE` : things that are missing

Correct me if i don't understand your vision right.

---

We can also say that Prosthetic installation require 6/8 in medicine and Bionics 10/12 in in _RecipeDefs_ by using :

```
<skillRequirements>
 <li>
  <skill>Medicine</skill>
  <minLevel>10</minLevel>
 </li>
</skillRequirements>
```

You can look how i've done in [DESurgeries](https://github.com/kaptain-kavern/DESurgeries/blob/master/Defs/RecipeDefs/Recipes_Surgery.xml). By setting class with _Parents_ and _abstract_ we can say that all in once in beginning of file

**Comment by inkyspoon** [comment]
done with new commit! xD

**Comment by kaptain-kavern** [comment]
I've tested and it's ok for me too.

I just think that maybe we should try keep to same format in naming things (part, Hediffdeff, etc) just for the sake of simplicity. But that can be updated later. 

If you two want do the 1.1 release i'm ok with that. (i'm kinda busy for the next hours for now)

**Comment by inkyspoon** [comment]
I'm not sure what you mean with the names but yeah we should update I think. I don't know how to merge the branches or make the release though

**Comment by kaptain-kavern** [comment]
ok i have a couple of minutes. i'm doing it right now

I'll do a commit with just the change i have in mind so we can discuss them and revert if needed :p

I'm gonna merge the Dev branche in master branche. and for the release i'm pretty sure you can figured out just by clicking on new release ;) but i'll do this one now.

I think that you should have the honour to post the update release on the forum as it is your works only :p

**Comment by kaptain-kavern** [comment]
[done](https://github.com/kaptain-kavern/ADogSaid/releases/latest)!

I let you do the forum post :p

**Comment by kaptain-kavern** [comment]
[Released](https://github.com/kaptain-kavern/ADogSaid/releases/latest)!
