### ISSUE TITLE
Possible conflict reported

### ISSUE THREAD

**Issue by nattiejim** [kaptain-kavern/ADogSaid#16]
Sarelth reported a possible conflict with another mod here: https://ludeon.com/forums/index.php?topic=21788.30

I do not know the name of the mod, so I have asked for further information.

**Comment by inkyspoon** [comment]
yeah I saw that on vegetable garden thread too. he thinks its us but dismar..the author of veg garden said it would be a mod that overwrites the plant parent def. and we don't even have that so I'm kinda sure its not us. but I will test it right now

**Comment by inkyspoon** [comment]
so like I said. just tested with mod order ccl cclvanilla epoe veggarden and us..no errors.
if it was us we would have overwritten veggarden and there would be errors.

**Comment by nattiejim** [comment]
All right then - I'll close this issue.

**Comment by kaptain-kavern** [comment]
Sareth pm'ed me in Ludeons forum and he sent me his mod list. There was so many mods that I can't be 100% sure of the compatibilities but it turns out that he use Fluffe mod that add new animals. I'm pretty sure this clash with our changes in ThingsDefRaces

The way I see it we may need to enforce people to place ADogSaid in the highest **reasonable** position in mod order (Just after CCL+tweak) In order to try to make other animal mods try to catch and inherit the changes in _AnimalThingBase_ class (because this is where we link the animal race to all the possible recipes).

The other most clean/compatible solution is to copy the class _AnimalThingBase_ in _our-modified-AnimalThingBase_ and redo all the files for ThingsDefRaces in order to reattach the animal to our modded AnimalThing class. That way the mod can be placed anywhere in mod order without throwing errors but we'll need to do patch for each new animals mods (or enforce modders to use our modded races)

**Comment by kaptain-kavern** [comment]
It's Dismar comment about parent def that make me think about that

**Comment by inkyspoon** [comment]
the thing is..I don't get how he gets the veggie error when we don't even have that? xD bc I did test with vegetable garden and there were no errors

**Comment by kaptain-kavern** [comment]
If you have seen the mod list ... I'm pretty sure he got several compatibility errors in the same time.

ADS(ADogSaid from now for me) was clashing with Fluffe's random animal mods

And VegGarden with Ghillie s mod

**Comment by inkyspoon** [comment]
but if theres several mods conflicting, I'm really not sure how and why we should help him...If he's got a ton of uncompatible mods we can't help anyway if they crash with each other? Or does the whole problem go away everytime he disables our mod? did he try to place it high above everything? like right under ccl, do you know?

**Comment by kaptain-kavern** [comment]
That's what i've advise him to do. And also to trim down is modlist too. For me this particular problem is solved/closed. I re-comment on the closed issue but i guess i should have open a new one. 
But the reasoning is the same and it's about parent def bases.

[Dismar's comment](https://ludeon.com/forums/index.php?topic=16931.msg238879#new) that made me think about all of that.

To me ADS is a special case as it aims to apply modification to all animals (including  modded one's if possible) so it's seem legit to me to enforce the high placement in mod order

**Comment by inkyspoon** [comment]
lol https://i.gyazo.com/3c5392463dde867dfb19550b84070174.png

**Comment by inkyspoon** [comment]
that mod already doesn't even work on its own! xD

**Comment by kaptain-kavern** [comment]
no look there is two folders in the archive. It's weirdly packaged :p

But it contain ThingsDefRaces files, so it will conflict with ADS (i [already updated](25eb853c862da9996814ab2fa5d15067bf03b823) the readme)

**Comment by inkyspoon** [comment]
oh I see its two versions of the mod?

**Comment by inkyspoon** [comment]
soo..I get no errors, when our mod is above.

**Comment by inkyspoon** [comment]
how about we just say..If you have mods that add new animals etc place our mod as high as possible

**Comment by kaptain-kavern** [comment]
lol

the screenshot of the modlist : https://www.dropbox.com/s/gmeuphi6ehy2g5m/2016-07-23.png?dl=0

**Comment by inkyspoon** [comment]
you are fucking kidding me!!! xD

**Comment by spoonshortage** [comment]
that dude can go fuck himself with that modlist lol ofc he has errors!!! jesus

**Comment by kaptain-kavern** [comment]
lol i know what you mean ;)  but srs i just explained that nobody can guarantee compatibility on that scale and advise him to reduce his modlist and also that the more mods he add the more i will find bug. Especially at first when you're beginning.  This steam workshop mess ... it will bring tons and tons of problem (especially savegames broken by mods autoupdate). Anyway ...

> how about we just say..If you have mods that add new animals etc place our mod as high as possible.

Simple and clear. Adopted :p

**Comment by inkyspoon** [comment]
so I just went ingame with our mod above the two fluffe mods..it gives no errors and I can still operate on the vanilla animals but ofc not on the added animals I don't think its that bad actually

**Comment by kaptain-kavern** [comment]
We both try to edit the same comment at the same time i see :p    nearly telepathic there

**Comment by inkyspoon** [comment]
yeah and the steam thing..seems nattie had to upload a complete new version of the mod now bc steam wouldn't let him just update the old one. I'm guessing its because the modfolder he was trying to update from is named differently than his initial vers 1.0.2 update. I hope people won't get angry when the mod is suddenly gone from their game and gives errors lol xD

**Comment by kaptain-kavern** [comment]
>  I don't think its that bad actually 

Neither do i. We clearly can't guarantee this

**Comment by nattiejim** [comment]
Just to clarify, I didn't delete the mod entirely, rather, I just set it to be hidden from the workshop. Hopefully, people won't have to deal with a broken game as if it had been just deleted entirely, but we'll see.

**Comment by kaptain-kavern** [comment]
> I'm guessing its because the modfolder he was trying to update from is named differently than his initial vers 1.0.2 update

This could be my fault as i haven't add the .zip in the 1.0.2 release (so the folder he download from Github source button was named Adogsaid-master.zip)  :-(

**Comment by inkyspoon** [comment]
yeah I saw ^^ it was just hidden. do you know what the problem was nattie? or what did steam say when you tried to update?

**Comment by nattiejim** [comment]
It didn't give me any errors when I tried to update - it just gave me the "Upload to Workshop" button on the Mods screen, when what I needed to use was the "Update" button.

**Comment by inkyspoon** [comment]
well the folder i got from the zip was just ADogSaid

**Comment by nattiejim** [comment]
My folder was ADogSaid as well.

**Comment by inkyspoon** [comment]
Do you think its bc of the old folder that was called LT-ADogSaid--1.0.2? or something

**Comment by inkyspoon** [comment]
maybe steam thought its a different mod bc of it

**Comment by nattiejim** [comment]
That's most likely what it was.

**Comment by inkyspoon** [comment]
so..we just stick with how it is now? and hope people using the old mod see the new update?

**Comment by nattiejim** [comment]
I think that's what we can do for now.

**Comment by inkyspoon** [comment]
yeah.. maybe write a comment or something explaining. maybe its for the best so now people can see the issue with old saves before they change over and not be surprised by it :)

**Comment by kaptain-kavern** [comment]
About steam workshop : It was a "thing" in the RW mod community since the last few weeks (see this [post](https://ludeon.com/forums/index.php?topic=14240.msg147215#msg147215)

**Comment by kaptain-kavern** [comment]
on this page : https://github.com/kaptain-kavern/ADogSaid/releases
When you edit the draft/release, you can drag and drop a zip/rar file in the browser

**Comment by kaptain-kavern** [comment]
I'm doing PR [there](https://www.reddit.com/r/RimWorld/comments/4uqf84/best_gameplay_mods/d5rz34v) ^^
