### ISSUE TITLE
Make different size off bionics/prosthetics legs again ^^

### ISSUE THREAD

**Issue by kaptain-kavern** [kaptain-kavern/ADogSaid#2]
i guess for this we'll need to browse through every animals in **_ThingDefs_Races_** for adding the 2 specific `<recipes>` corresponding to their sizes (1 for prosthetic and 1 for bionics)

Or for all that I understand at least for each bodytype. If it's possible that way each specialized legs can be defined with the right sets of claws/fingers/etc (or not, in order to materialize the fact that prosthetic is lesser quality than bionic)

**Comment by kaptain-kavern** [comment]
This will become easy to do while reworking the system for linking animal to recipe via the recipe file only

**Comment by inkyspoon** [comment]
honestly...I'd rather not. 
It was bad enough last time around with all the different sizes. I personally thought it was to complicated and too much added stuff. We already have added **15!** new Items.
 If we did that it would add at least 6 more... and then, once you've added three more sizes for each leg, logic would dictate _bigger arms_ for megatheriums... so then _spines_ wouldn't make sense too, so new sizes for those...you see where I'm going with this? ;)  
I'm pretty sure people don't like that much stuff lying around in their stockpiles just to have the right size available once they need it. (don't forget, the things don't stack)
