### ISSUE TITLE
Steamworkshop Drama s01e01 

### ISSUE THREAD

**Issue by kaptain-kavern** [kaptain-kavern/ADogSaid#21]
As predicted, [[A14] ADogSaid - EPOE workbenches](https://ludeon.com/forums/index.php?topic=22282.0)

**Comment by inkyspoon** [comment]
well...that's done then...lol. guess we don't have to integrate it anymore? Though I would have wanted to make our stuff craftable on the machining bench. For people who don't use EPOE. I really don't know what to say to that. Also would have been nice if he at least had mentioned something beforehand...

**Comment by kaptain-kavern** [comment]
I was more about doing what we have planned anyway and hope they're willing to update theirs after 1.2
I too want the mod to be able to give the ability to craft on its own.
