### ISSUE TITLE
Rewriting of the way we hook up animals to recipes

### ISSUE THREAD

**Issue by kaptain-kavern** [kaptain-kavern/ADogSaid#22]
# The Idea

As for now we are using `<recipes>` tag in _**[Races_Animal_Base.xml](https://github.com/kaptain-kavern/ADogSaid/blob/master/Defs/ThingDefs_Races/Races_Animal_Base.xml)**_ in order to define which recipes is available  for which animals.

By listing authorized animals under each recipes in **_[Recipes_Surgery.xml](https://github.com/kaptain-kavern/ADogSaid/blob/master/Defs/RecipeDefs/Recipes_Surgery.xml)_** we will decrease a lot incompatibility interferences with other mods, especially those that modify _**ThingDefs_Races**_ (we would not even need them if i'm right)

```
<recipeUsers>
    <li>Human</li>
</recipeUsers>

```
# Linkology/documentation :
- [Comment by Kyos](https://ludeon.com/forums/index.php?topic=19952.msg218473#msg218473) about the very same reasoning (but for Human_race files) 
- [A note to modders about xml definitions](https://ludeon.com/forums/index.php?topic=19499.msg212672#msg212672) - the use of abstract classes and inheritability across mods
- [Recap table i made with all animals + some xml value](https://docs.google.com/spreadsheets/d/13rgQecI_4Z6-olG9PCO-6uSVyC5cmXh6_Wp_v-Xt8FI/edit?usp=sharing)

**Comment by inkyspoon** [comment]
yes that would be wonderful _if_ it works.  ^^

**Comment by kaptain-kavern** [comment]
imma make it work !!!

In fact that's the way it works now in DESurgeries : https://github.com/kaptain-kavern/DESurgeries/commit/be6d2b20f058bb29ebb1ed52d9a66f2703df75de

**Comment by inkyspoon** [comment]
lol I already did everything haha xD

**Comment by inkyspoon** [comment]
maybe check your slack ;)

**Comment by kaptain-kavern** [comment]
i knew i should do it before speaking of it OR else you will do all the code!
Damn i have rights too, i want to code !!!

Joke aside, nice of you doing that, as always. i will go on slack later its kinda make me "unfocused" ^^

**Comment by inkyspoon** [comment]
sry lol but what am I supposed to do when you sleep the whole day away! xD I don't like to twiddle my thumbs  haha

**Comment by inkyspoon** [comment]
but you can still do something..like I asked you on slack..the def_races folder needs to be deleted in both lite and dev branch and I don't know how to do that..I uploaded the files without those folders but it still kept them from master branch i think

**Comment by kaptain-kavern** [comment]
Done in Dev  2ac77c09ab962e9a379d62e2b7e4b4ebd6a783a8

Done in Lite 482f19c931522e14207055e0a2e50c921984bf1a

Please verify/test again. I'm not sure i've done things right

**Comment by inkyspoon** [comment]
yes just tested everything seems to work fine. did you test yourself?

**Comment by kaptain-kavern** [comment]
Yep it works.

I double test my _new_ new version of DESurgies alongside both have pass the test for me. 

Now we're on the road to the crafting of the parts. 
Or do you think this alone deserve to be released?
