### ISSUE TITLE
Add the crafting !

### ISSUE THREAD

**Issue by kaptain-kavern** [kaptain-kavern/ADogSaid#24]
Ok @spoonshortage can i work on that or is it already done ? :p 

Actually just one question : Which Vanilla bench do we choose ?
- HiTechResearchBench (i'm not even sure this can be used as craftpoint)
- ComponentAssemblyBench
- TableMachining
- Something i haven't thought

**Comment by inkyspoon** [comment]
machining table makes the most sense I guess

**Comment by inkyspoon** [comment]
wood + steel for simple prosthetics and steel + plasteeel for bionics and maybe plus devilstrand for organs? does that make sense?

**Comment by kaptain-kavern** [comment]
> machining table makes the most sense I guess
> I agree

I'm ok with with prosthetics and bionics without hesitations. 
About Devilstrand ....  It's too bad you can't craft Synthred or Hyperweave in Vanilla, it intuitively makes more sense (for me) to craft organs with those rather than with mushroom fiber. 

But i guess if it's either Steel+Plasteel+Devilstrand or _"just"_ Steel+Plasteel i prefer with Devilstrand. (It's just feel weird, to me, lore-wise (i don't know if this word actually exist :p )

**Comment by inkyspoon** [comment]
yes I know what you mean my first instinct was to say hyperweave but then I remembered you can't craft that in vanilla...^^

**Comment by inkyspoon** [comment]
added crafting to dev branch (only the full version so far) please test ingame and report back about cost/crafting requirement, speed etc

**Comment by nattiejim** [comment]
Good job on the code, guys! 

I'm ready to update the releases when you are.

**Comment by inkyspoon** [comment]
I'm waiting to hear back from kaptain but did you test it in game nattie? what do you say about the material cost etc?

**Comment by nattiejim** [comment]
All of the material costs seem to be balanced nicely on my end!

**Comment by kaptain-kavern** [comment]
all right
sorry for the delay. Everything is fine, Dev branche and Lite branche are up to date and ready to go!
I do the release here so you can do on the forum and Steam ?

**Comment by nattiejim** [comment]
Release is done! Also, please note - I will be off for tomorrow and next week.

**Comment by kaptain-kavern** [comment]
Ok doke o7
Thank you. see you later then
