### ISSUE TITLE
Add animal meal

### ISSUE THREAD

**Issue by kaptain-kavern** [kaptain-kavern/ADogSaid#27]
Some want the [Silage mod](https://ludeon.com/forums/index.php?topic=16549.0) to be updated to A14.

What do you think about including it in ADS, colleague ?

or I'll convince/force/suggest **_Dismar_** to add it in Veg Garden ^^

**Comment by inkyspoon** [comment]
veg garden would be way more appropriate I think,  after all we have nothing to do with food :)

**Comment by kaptain-kavern** [comment]
[message sent](https://ludeon.com/forums/index.php?topic=12934.msg247189#msg247189) :stuck_out_tongue_closed_eyes:

**Comment by nattiejim** [comment]
I agree with @spoonshortage - we don't have anything to do with food, the update is Dismar's job.

**Comment by kaptain-kavern** [comment]
in fact I've done it 

https://ludeon.com/forums/index.php?topic=16549.msg248048#msg248048
