### ISSUE TITLE
Idea - add a surgery option for neutering animals?

### ISSUE THREAD

**Issue by kaptain-kavern** [kaptain-kavern/ADogSaid#28]
> It seems very realistic, easy to implement, and would solve a number of problems with pets overpopulating.
> 
> https://www.reddit.com/r/RimWorld/comments/4xe4wn/idea_add_a_surgery_option_for_neutering_animals/

What do you think?

---

**notes:**
- _In Core\Defs\ThingDefs_Races\Races_Animal_xxx.xml :_  

```
<mateMtbHours></mateMtbHours>
```
- _In Core\Defs\ThinkTreeDefs\Animal.xml :_

```
            <!-- Try to mate -->
            <li Class="ThinkNode_ChancePerHour_Mate">
              <subNodes>
                <li Class="JobGiver_Mate" />
              </subNodes>
            </li>
```
- _In Core\Defs\JobDefs\Jobs_Animal.xml :_ 

```
  <JobDef>
    <defName>Mate</defName>
    <driverClass>JobDriver_Mate</driverClass>
    <reportString>mating with TargetA.</reportString>
    <casualInterruptible>false</casualInterruptible>
  </JobDef>
```

**Comment by biship** [comment]
Yeah I saw that post. Its a good solution for those without Colony Manager (where you just set a max number and the rest get slaughtered). IRL, non-domestic animals have (higher) chances for complications with neutering. Female neutering can be very risky & problematic.

**Comment by inkyspoon** [comment]
it would be a great addition, but I'm not sure how to implement the mating etc changes by surgery.

**Comment by kaptain-kavern** [comment]
I hope we can find a way via Hediff else I bet it will be C# related :disappointed:

**Comment by nattiejim** [comment]
That seems like a good idea! Unfortunately, I don't know too much about C# code, so we'll need someone who can use C#.

**Comment by kaptain-kavern** [comment]
Looks like I have to learn at least how to detour then ^^

**Comment by inkyspoon** [comment]
fluffy did a mod for that by adding genital parts to animals/humans :P
