### ISSUE TITLE
Some Birds and Megatherium cannot receive artificial legs

### ISSUE THREAD

**Issue by kaptain-kavern** [kaptain-kavern/ADogSaid#3]
seems to work mostly, but ostrich, emu, cassowary, and turkey can only recieve animal eyes (no pegleg prosthetic or bionic legs) and megatherieum also eyes and arms but no legs.

**Comment by inkyspoon** [comment]
all the birds seems like. chicken too. also monkey has same problem as megatherium arms and eyes but no legs

**Comment by kaptain-kavern** [comment]
I think i've got it covered. All of those have `<li>LeftLeg</li>` and `<li>RightLeg</li>` in BodyDefs unlike most animals. This commit 9cb7c1914d3a84c5d70dc7326642f84c088e70ba  in [Dev branche](https://github.com/kaptain-kavern/ADogSaid/tree/Dev) should do it. But I have to test it before

**Comment by kaptain-kavern** [comment]
Ok i tested it and it works!

![ADogSaid - Working Birds Bionic Legs](http://i.imgur.com/91q7vFJ.jpg?1)

Will be in the next update :p

**Comment by kaptain-kavern** [comment]
Will be in the next update :p
