### ISSUE TITLE
Animal Prosthetics Workbench Nay/Yay?

### ISSUE THREAD

**Issue by inkyspoon** [kaptain-kavern/ADogSaid#30]
So I know, most people hate more workbenches, that's why we made the prosthetics craftable on the machining table, **but** - a lot of people are complaining, that their machining table is getting too full, and with the new addition of kidney, liver and stomach, there are bound to be even more complainers.

I went ahead and made an Animal Prosthetics bench, that is 2 tiles wide:
![screen](https://i.gyazo.com/21dbc1f775a3f405fe31ee127e284acf.jpg)
![screen2](https://i.gyazo.com/7befe58d284c8e9288e49777b0d35d63.jpg)

The question now is: What do you think? Nay? Yay?

**Comment by biship** [comment]
Considering I use Colony Manager, I don't have a need for another bench.

**Comment by Skullywag** [comment]
Shinzy votes yay. I also vote yay

**Comment by kaptain-kavern** [comment]
YaY too. :+1: 

Sorry I can't reply sooner. It is a good idea and I like the texture ;) 
I'm all for the new benche. 

If people were complaining why don't they change machine table to component bench or an other less used benches?

**Comment by inkyspoon** [comment]
my guess is, it's people with a lot of armor/weapon mods who all prbly use the machining table for crafting those.
we could _theoretically_ move our stuff to the components assemby too, but that would be bit "too late in game" to be useful I think?

**Comment by kaptain-kavern** [comment]
Yes it's too "end-game".
And I like your bench too much to be satisfied by the Component bench :construction_worker:

**Comment by inkyspoon** [comment]
well if we go ahead and do it I suggest we only use it for the full version tho, since no crafting is self explanatory and lite version only has the 2 simple and 2 bionic limbs and those can stay on the machining table.

**Comment by kaptain-kavern** [comment]
I agreed. 
If you haven't already done it :suspect: , I can do the code change
