### ISSUE TITLE
Changing color of HEdiff label

### ISSUE THREAD

**Issue by kaptain-kavern** [kaptain-kavern/ADogSaid#31]
![Imgur](http://i.imgur.com/TAH9bLL.png?1)

Exact same color as Vanilla. Do you find it better (more "intuitive") ?

**Comment by inkyspoon** [comment]
i think they wanted the colors to match the ones from epoe..different colors for bionics and simple prosthetics and green for organs or so

**Comment by kaptain-kavern** [comment]
Crap, and me who thinking to surprise you :stuck_out_tongue: 
I'll revise my copy and I will be back :robot: :+1:  Asta la vista :v:

**Comment by kaptain-kavern** [comment]
How about that?
![Imgur](http://i.imgur.com/ojdet1U.png?1)

I tried to do it simple : 
- All simple parts (with reduced efficiency) are the same color as EPOE simple parts (orange)
- All bionics parts (with enhanced efficiency) are the same color as Vanilla and EPOE bionics (blue)
- No third color as our organs/limbs are just separate in two versions _(What do you think? It could be as easy to add the green)_

Compared to how it is atm : 
![Imgur](http://i.imgur.com/rezK8gE.png?1)

**Comment by inkyspoon** [comment]
sounds fine...and you added the tigers! xD

**Comment by kaptain-kavern** [comment]
And the panda on the first pic ! :panda_face: 
They are from my other in progress mod : [CK - Animal and Plant Pack](https://ludeon.com/forums/index.php?topic=26265.0).  It add animals and plants. And I've done a first pass at the inevitable compatibility patch :tongue: 

Speaking of that, there is also : 
- [Alpha Animals](https://ludeon.com/forums/index.php?topic=26549.0)
- [CPBeasties](https://ludeon.com/forums/index.php?topic=26354.0)
- [Taiga Creatures](https://ludeon.com/forums/index.php?topic=26497.0)

I will make all the patch in one go (it is such a captivating activity ^^)

---

Not related to anything : Because of your Halloween mod I may be able to interrest my wife in the game ^^ Thx :wine_glass:
