### ISSUE TITLE
Adding Prosthetic tail

### ISSUE THREAD

**Issue by kaptain-kavern** [kaptain-kavern/ADogSaid#33]
- Prosthetic tails : **Very requested it seems** :smiley:  ==> see this commit on master https://github.com/kaptain-kavern/ADogSaid/commit/73e81f91a467cb6610581202783d24cd1dae5db8
   >Recipe cost 3 **Steel** and 2 **Woodlog**

**Comment by kaptain-kavern** [comment]
It should be OK now.

Files added in **EPOE compatch** and **no-crafting version** as well.

Again, as all is finished regarding this and[ A16 will be not here for another nearly 2 month (minimum)](https://www.reddit.com/r/RimWorld/comments/5ax9a9/some_notes_on_recent_controversies/d9kpvgq/), I don't see a reasons to wait for next year in order to release the last 2 minors additions

**Comment by inkyspoon** [comment]
thats maybe not the last ones. maybe we will have to do more with a16 updates. bc of balancing done in core etc and maybe new animals added also

**Comment by kaptain-kavern** [comment]
the last of A15 releases I meant ;-) To me, until **Core 1.0** No mods can be considered finished :wink: 

That's my point also, A16 may bring changes, so it's a good thing to finish the A15 subject/matter ^^

For A16 even without knowing what will changes I already know I want to do more lol :) 

Have idea for amelioration already (like having the recipes putted in the ThingDef via RecipeMaker (non urgent but again a bit more compatible and less files to handle :p) 

---

Unless I totally missing something, maybe? (sorry if it is)
Is that really so much work for releasing on Steam compare to a thread update on the forum ?
