### ISSUE TITLE
Re-integrate A17 code

### ISSUE THREAD

**Issue by kaptain-kavern** [kaptain-kavern/ADogSaid#36]
If it's OK with you @spoonshortage I can re-manage things on the github.

If you'd prefer not, or to wait for A17 release it's cool also. Otherwise could you send me your files please ?

**Comment by inkyspoon** [comment]
[ADogSaid-full A17.zip](https://github.com/kaptain-kavern/ADogSaid/files/1020732/ADogSaid-full.A17.zip)

**Comment by kaptain-kavern** [comment]
Thank you. I will just make the Github up to date. I think I remember reading you don't want to "officially" release it before the "real" A17, right?

It's not that I want it to, it's just just I don't want to make something you haven't got in mind ;)

**Comment by inkyspoon** [comment]
yeah I would rather wait.

**Comment by kaptain-kavern** [comment]
Okey dokey. No leaked release until A17 ;-)
