### ISSUE TITLE
version 1.0.1 stopped working for me completely?? 

### ISSUE THREAD

**Issue by inkyspoon** [kaptain-kavern/ADogSaid#7]

**Comment by inkyspoon** [comment]
[![https://gyazo.com/5cbb434cbc4a17837a76b3e4e285de5f](https://i.gyazo.com/5cbb434cbc4a17837a76b3e4e285de5f.png)](https://gyazo.com/5cbb434cbc4a17837a76b3e4e285de5f)

**Comment by kaptain-kavern** [comment]
Damn it works on my computer. I'll go Back to investigation then

**Comment by inkyspoon** [comment]
yeah so just tested 1.0 release again works like it did with just bird monkey mega legs missing. but new release only shows euthanize on all animals maybe those race files weren't that useless?

**Comment by kaptain-kavern** [comment]
Thanks it will help.

Yes that is what I was thinking about, but it strange as those files were just exact copy/paste from the Core mod folder ...

**Comment by inkyspoon** [comment]
yeah I know but thats the only change right? also i tested with just those two leg lines added in the surgery.xml and it gave me errors

**Comment by kaptain-kavern** [comment]
Yes it was the only change with the two new lines in Recipe_surgery about legs. 

Did you use other mods with it? (I'm not in front of computer now so I only can think about it)

**Comment by inkyspoon** [comment]
I tried with ccl and without, same thing, doesn't work

**Comment by inkyspoon** [comment]
maybe try sending me the exact working modfolder that you have on your pc (dropbox or whatever) and I'll see if it works here. maybe something messed up with the github files

**Comment by kaptain-kavern** [comment]
Bam !

It was those damn not-so-useless-obviously files...

![clipboard](http://i.imgur.com/sJTxlMS.jpg)

**Comment by kaptain-kavern** [comment]
I'm reupload them now.  But i wish i understand why's that.
Anyway it was the only logical choice. My bad sorry

**Comment by kaptain-kavern** [comment]
Version 1.0.2 have corrected this
